version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis-app
    ports:
      - "6379:6379"
    networks:
      - app-network
    environment:
      - REDIS_PASSWORD=yourpassword

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - app-network
  
  system:
    image: "system:latest"
    container_name: system
    env_file:
      - ./config/.env
    build:
      context: .
      dockerfile: docker/Dockerfile
    deploy:
      replicas: 1
    ports:
      - "3000:3000"
      - "8787:8787"
    volumes:
      - ./:/app/
    networks:
      - app-network
    depends_on:
      - postgres

networks:
  app-network:
    driver: bridge
volumes:
  postgresdata: